# Column Usage

```{r, echo=FALSE, warning=FALSE, error=FALSE, include=F}

library(ggplot2)
library(dplyr)
library(reshape2)

source("columnGuess.R")

```

```{r, echo=FALSE, warning=FALSE, error=FALSE}
project <- Sys.getenv("PROJECT", NA)
project <- "BMA"
if(is.na(project)) {
  project <- ""
} else { 
  project <- paste0("-", project)
}
datasetFile <- paste0("../jiraData/jiraRDataset", project, ".csv")

tsTickets <- read.csv(datasetFile, header=T, skipNul=T, na.strings="") %>%
  mutate(
    created = as.POSIXct(created), 
    createdMonthDisplay = format(created, format="%Y %B"),
    createdMonth = as.numeric(format(created, format="%Y%m")),
    resolutionDate = as.POSIXct(resolutionDate), 
    resolutionMonthDisplay = format(resolutionDate, format="%Y %B"),
    resolutionMonth = as.numeric(format(resolutionDate, format="%Y%m")),
    totalTime = resolutionDate - created
  ) %>% 
  filter(status != "Closed") %>% 
  filter(status != "to do") %>% 
  filter(status != "open") %>%
  filter(ticketType != "Epic")


resolvedTickets <- tsTickets %>% arrange(resolutionMonth)
resolvedTickets$resolutionMonthDisplay <- factor(tsTickets[order(tsTickets$resolutionMonth), "resolutionMonthDisplay"], levels=unique(tsTickets[order(tsTickets$resolutionMonth), "resolutionMonthDisplay"]))

count_na <- function(x) sum(!is.na(x))
blah <- melt(as.list(resolvedTickets %>% select( contains("secondsInColumns")) %>% apply(., 2,count_na)))

library(forcats)
blah$L1 <- forcats::fct_inorder(blah$L1)

statusLabels <- gsub("secondsInColumns.", "", blah$L1)
names(statusLabels) <- blah$L1

ggplot(blah, aes(x=L1, y=value)) + geom_col() + theme(legend.position = "bottom", axis.text.x = element_text(angle=60, hjust=1)) + ggtitle("Column Usage") + xlab("Column") +ylab("Number of tickets") + scale_x_discrete(labels=statusLabels)
```

```{r}

count_na <- function(x) sum(!is.na(x))

#blah <- melt(as.list(resolvedTickets %>% select( contains("redoForColumns")) %>% apply(., 2,count_na)))

library(forcats)
#blah$L1 <- forcats::fct_inorder(blah$L1)

#statusLabels <- gsub("redoForColumns.", "", blah$L1)
#names(statusLabels) <- blah$L1

#ggplot(blah, aes(x=L1, y=value)) + 
#  geom_col() + theme(legend.position = "bottom", axis.text.x = element_text(angle=60, hjust=1)) + ggtitle("Redo Usage") + #xlab("Column") +ylab("Number of tickets") + scale_x_discrete(labels=statusLabels)

clah <- resolvedTickets %>% select(contains("redoForColumns")) %>% as.list() %>% melt()
clah$L1 <- forcats::fct_inorder(clah$L1)
statusLabels <- gsub("redoForColumns.", "", clah$L1)
names(statusLabels) <- clah$L1
ggplot(clah, aes(x=L1, y=value)) + geom_jitter(height=0.4, width=0.4, alpha=0.5) + scale_x_discrete(labels=statusLabels) + theme(axis.text.x = element_text(angle=60, hjust=1))

resolvedRedoTickets <- resolvedTickets %>% mutate(
  transitionCount = select(., contains("redoForColumns")) %>% apply(1, sum, na.rm=T),
  redoCount = select(., contains("redoForColumns")) %>% mutate_all(function(x) { return(x-1) }) %>% apply(1, sum, na.rm=T),
  
  )

ggplot(resolvedRedoTickets, aes(x=resolutionDate, y=redoCount)) + geom_jitter(height=0.2, width=0.1) + geom_smooth()

redoMonthGroup <- resolvedRedoTickets %>% group_by(resolutionMonthDisplay) %>% summarise(
  count = n(),
  nonCount = sum(redoCount == 0),
  redoPercent = sum(redoCount > 1) / count,
  redoCount = sum(redoCount >1),
  storyPoints = sum(storyPoints, na.rm=T)
  ) %>% filter(!is.na(resolutionMonthDisplay))
redoMonthGroup %>% knitr::kable()

ggplot(redoMonthGroup, aes(x=resolutionMonthDisplay, y=redoPercent, group=1)) + 
  geom_smooth(colour = "grey40") + 
  geom_point() + 
  geom_line() + 
  ggrepel::geom_text_repel(aes(label = redoCount), force=2) + 
  theme(axis.text.x = element_text(angle=60, hjust=1)) + 
  scale_y_continuous(labels = scales::percent) + 
  coord_cartesian(ylim=c(0, max(redoMonthGroup$redoPercent)*1.2), expand=T) + 
  ggtitle("Percentage of completed tickets with Redo", subtitle="Number = Count of tickets with Redo")

ggplot(redoMonthGroup %>% select(resolutionMonthDisplay, storyPoints, count, redoCount) %>% reshape2::melt(id="resolutionMonthDisplay"), aes(x=resolutionMonthDisplay)) + geom_line(aes(y=value, color=variable, group=variable)) + 
  ggrepel::geom_text_repel(data= redoMonthGroup, aes(y=redoCount, label=redoPercent %>% round(2) %>% scales::percent() ), direction="y") + 
  theme(axis.text.x = element_text(angle=60, hjust=1), legend.position = "bottom") + ylab("Number of tickets / Story Points") + xlab("Month") + ggtitle("Velocity & Tickets with Redo work") + scale_y_continuous(breaks = seq(0,1000,10)) + scale_color_manual(labels = c("storyPoints" = "Story Points", "count"="Resolved", "redoCount" = "With Redo"), values=c("redoCount"="#fc8d62", "count"="#8da0cb", "storyPoints"="#66c2a5"), name="Tickets")


ggplot(resolvedRedoTickets %>% filter(redoCount > 0), aes(x=resolutionDate, y=0, size=redoCount)) + ggbeeswarm::geom_quasirandom(groupOnX=F, side=1)
ggplot(resolvedRedoTickets, aes(x=resolutionMonthDisplay, y=0, size=redoCount)) + ggforce::geom_sina()
```

```{r, echo=FALSE, warning=FALSE, error=FALSE}

latestMonth <- max(resolvedTickets$resolutionMonth, na.rm=T)
byMonth <- resolvedTickets %>% 
  group_by(resolutionMonth, resolutionMonthDisplay) %>% 
  select( resolutionMonth, resolutionMonthDisplay, contains("secondsInColumns")) %>% 
  select(-contains("out")) %>%
  summarise_all(funs(count_na)) %>%
  filter(!is.na(resolutionMonth)) %>% filter(resolutionMonth != latestMonth)

if (nrow(byMonth)) { 
library(forcats)
#byMonth$L1 <- forcats::fct_inorder(byMonth$L1)

byMonthMelt <- melt(byMonth, id=c("resolutionMonth", "resolutionMonthDisplay"))

#ggplot(byMonthMelt, aes(x=variable, y=value, group=resolutionMonth)) + geom_col(position="dodge") + theme(legend.position = "bottom", axis.text.x = element_text(angle=60, hjust=1))


#ggplot(byMonthMelt, aes(x=variable, y=value, group=resolutionMonth)) + geom_col(position="dodge") + theme(legend.position = "bottom", axis.text.x = element_text(angle=60, hjust=1)) + facet_wrap(~resolutionMonth)

naByMonthMelt <- byMonthMelt
naByMonthMelt[naByMonthMelt == 0] <- NA

load(file="colColourFit.Rdata")
load(file="colColourTdm.Rdata")

guessedStatusColours <- guessColumnColours(naByMonthMelt$variable %>% unique, colColourFit, colColourTdm)


ggplot(naByMonthMelt, aes(x=resolutionMonthDisplay, y=value, color=variable, group=variable))  + 
  theme(legend.position = "bottom", axis.text.x = element_text(angle=60, hjust=1)) +
  scale_x_discrete() + 
  ylab("Number of tickets visiting a column") + xlab("Month") + ggtitle("Column Usage over time") +
  scale_color_manual(values=guessedStatusColours, na.value="gray", labels=statusLabels, name="Column") +
  geom_line(linetype="dashed", alpha=0.2) + 
  geom_smooth(se=F, fullrange=F, span=1, method="loess")
 # geom_point() 
}
```

